### ISSUE TITLE
Cannot read property '$set' of null

### ISSUE THREAD

**Issue by SeavantUUz** [TahaSh/vue-paginate#10]
**version: 2.1.1**

I updated vue-paginate, but when I used it in my project, I received this error message in my browser.
I spent some time in debugging to find what reason may cause this problem.
Finally, I thought what I paste below is the main reason.

```javascript
vm['change' + utils.capitalize(this.listName) + 'Page'] = (page) => {
      // Reset the list with original data for two reasons:
      // 1. To change it, so the update hook gets triggered.
      // 2. To slice it with new positions from the beginning.
      vm[this.listName] = this.originalList;

      this.list.currentPage = typeof page == 'number' ? page - 1 : page;

      this.setLimitedPages(limit);
    };
```

My debugger told me that **this.vm is null** when  procedure executed into this context. So when browser stepped into **this.setLimitedPages** --- because a reference of this.vm --- executing was interrupted.
Maybe you should re-check them.
THX.

**Comment by TahaSh** [comment]
Hey, @SeavantUUz! Could you please paste the code that uses the plugin? I can't reproduce the error.

**Comment by SeavantUUz** [comment]
there is:

```html
<template>
    <section class="books">
        <ul class="my-books-ul">
            <li class="book" v-paginate:3="products" v-for="product in products">
                <a :href="'/product/'+product.product_id">
                    <img :src="product.cover" class="cover" title="">
                </a>
                <p>${ index }</p>
                <cite class="book-title"><a :href="'/product/'+product.product_id">${ product.product_name }</a></cite>
                <span class="book-author">${ product.author }</span>
            </li>
        </ul>
        <a @click="prevProductsPage()" href="#">
            上一页
        </a>
        <a @click="nextProductsPage()" href="#">
            下一页
        </a>
    </section>
</template>
<style>
</style>
<script>
    export default{
        props: ['products']
    }
</script>
```

**Comment by TahaSh** [comment]
Hello @SeavantUUz! Really sorry for the late response. Your problem is pretty easy to solve. All you have to do is move `v-paginate:3="products"` directive from the list item `<li>` to the parent tag `<ul>`.
So you should have this:

``` js
<ul class="my-books-ul" v-paginate:3="products">
    <li class="book" v-for="product in products">
```

The reason is because the paginated list has to be evaluated first before iterating over its items with `v-for`.

**Comment by SeavantUUz** [comment]
Yes, I read your codes carefully and I found I had been wrong in there.
THX

**Comment by TahaSh** [comment]
That's good to hear :). Good luck and thanks!
