### ISSUE TITLE
Paginate list stay empty after source array was filtered

### ISSUE THREAD

**Issue by Prechan** [TahaSh/vue-paginate#105]
Hi,

In my app, the computed property array is filtered by user's inputs, size may change and sometimes being empty. 
When computed properties return an empty array, paginate list become empty. But if user changes the filter and computed properties return an non empty array, paginate list stay empty even so.

As if it doesn't update anymore after a first empty event.

Do you have an idea how to solve this problem ? It seems linked to vue-paginate.

Thanks for your help !

**Comment by wunderlichh** [comment]
Try @mornir solution from #82. It worked great for me.

**Comment by Prechan** [comment]
Thanks ! Works great !
