### ISSUE TITLE
page change event 

### ISSUE THREAD

**Issue by iltegin** [TahaSh/vue-paginate#11]
How to handle async data per page ?
For example I have 1000 field in my json.

Override function "change[]Page" not working ?

**Comment by TahaSh** [comment]
Hey @iltegin! Why do you want to override this function? This plugin supports async data natively. Here's an example: [https://github.com/TahaSh/vue-paginate/releases/tag/v1.1.1](https://github.com/TahaSh/vue-paginate/releases/tag/v1.1.1)

**Comment by iltegin** [comment]
Hi @TahaSh  thanks for your answer. I know async data support this plugin, but problem something else. I solved the problem.

Thanks for this plugin.
