### ISSUE TITLE
How can I get the current page number?

### ISSUE THREAD

**Issue by JosMigue** [TahaSh/vue-paginate#132]

**Comment by harunkocacaliskan** [comment]
From documentation;

**Listening to links @change event**

When the current page changes, PaginateLinks emits an event called change to inform you about that. It also passes the switched page numbers with it, if you need them.

```
<paginate-links
  for="languages"
  @change="onLangsPageChange"
></paginate-links>
```

```
methods: {
  onLangsPageChange (toPage, fromPage) {
    // handle here…
  }
}
```

Check my [jsfiddle](https://jsfiddle.net/as2kwo04/)

**Comment by JosMigue** [comment]
Thanks, it works
