### ISSUE TITLE
Plans to support Vue.js 2.0 ?

### ISSUE THREAD

**Issue by pelletiermaxime** [TahaSh/vue-paginate#18]
Hi,

Have you looked a bit at Vue 2 and how to support it ? From the doc:

> Vue.set and Vue.delete cannot work on Vue instances. It is now mandatory to properly declare all top-level reactive properties in the data option.

This directive is creating new data, so I guess it won't work anymore. Also the directive API completly changed, so it would need a complete rewrite.
Maybe we need to change it to a component, just like vue-router did with "v-link" ? I could give it a shot if you think it would be possible.

Any toughts ?

**Comment by pelletiermaxime** [comment]
Well it looks like it may be possible to keep it a directive after all. I got a few tests working in a fork at https://github.com/pelletiermaxime/vue-paginate. I still really suck at javascript, so I'm sure you could do a lot better hehe.

**Comment by DannyFeliz** [comment]
@TahaSh is rewriting this plugin to support Vue 2 #19 issuecomment-255443612

**Comment by TahaSh** [comment]
As @DannyFeliz mentioned, I'm now rewriting it for Vue 2.0. And it's going to be released very soon.
