### ISSUE TITLE
Rewrite

### ISSUE THREAD

**Issue by callumacrae** [TahaSh/vue-paginate#20]
Hello!

This plugin kept not working for us at @SamKnows, so I rewrote it. It's largely backward compatible—although it doesn't yet support all the configuration options that this one does—and is 66 lines of code long. The code is also a lot more understandable and readable (in my opinion!) Currently working on Vue 2.0 support but blocked by https://github.com/vuejs/vue/issues/4120.

Would you be interested in using that code as a starting point of the next version of vue-paginate? How far have you got through the rewrite you mentioned [here](https://github.com/TahaSh/vue-paginate/pull/19#issuecomment-255443612)?

**Comment by TahaSh** [comment]
Hey @callumacrae! I appreciate you taking the time to rewrite the plugin. But, unfortunately, I've already got the new version to work (is this good or bad? 🙃) . And this time I'm using a new approach – it's now components based. It's a whole lot cleaner than the previous version. And it's built specifically for Vue 2.0.

I'm now in the refactoring and bundling phase. So, my plan is to get it out by the end of the next week.

Thanks for your patience :).

**Comment by callumacrae** [comment]
Nice, good stuff :)
