### ISSUE TITLE
Page change event

### ISSUE THREAD

**Issue by hedii** [TahaSh/vue-paginate#22]
Hi,
Is there an event on which i can listen for page change?
My use case: scroll to top of the page on pagination click.
I tried putting @click="myMethod" on paginate-links tag, with no success.
Also tried setting a watcher on paginate, but obviously this is not the way to do it and it does not work.

**Comment by TahaSh** [comment]
Hey @hedii! Thanks for filling this issue – this feature would be very helpful to others, too :).
Now, after you update `vue-paginate` to v3.1.0, you should be able to listen to `@change` event on your `<paginate-links>` component. For more details, [check out this quick example](https://github.com/TahaSh/vue-paginate/tree/v3.1.0#listening-to-links-change-event).

**Comment by hedii** [comment]
Thank you @TahaSh
