### ISSUE TITLE
TypeError: Cannot read property 'componentOptions' -paginate-links

### ISSUE THREAD

**Issue by hemans** [TahaSh/vue-paginate#23]
Dear Tahash,

Wanted to send this as an email rather than raise an issue as I am not sure where the problem is.
the paginate component works without the paginate-links. immediate I include the paginate-links there component does not work.
Error:
`vue-paginate.js?6bc9:5626Uncaught (in promise) TypeError: Cannot read property 'componentOptions'` 

template:

`<div class="col-md-12 col-sm-12">`
`            <paginate name="singers" :list="singers" :per="4" tag="div">`
			`<table class="table table-condensed">`
				`<thead>`
		           ` <tr>`
		                `<th>Id</th>`
		                `<th>Name</th>`
		               ` <th>Gender</th>`
		                `<th>Email</th>`
		               ` <th>Address</th>`
		                `<th>Can Sing</th>`
		                `<th>Instruments</th>`
		                `<th>Action</th>`
		           ` </tr>`
        		`</thead>`
        		`<tbody>`       
        			`<tr v-for="list in paginated('singers')" :key="list.id">`
        				`<th>{{list.id}}</th>`
        				`<th>{{list.name}}</th>`
        				`<th>{{list.sex}}</th>`
        				`<th>{{list.email}}</th>`
        				`<th>{{list.address}}</th>`
        				`<th>{{list.can_sing}}</th>`
        				`<th>{{list.instruments}}</th>`
        				`<th> <span><button class="btn btn-danger btn-sm" ``@click="deleteSinger(list)" style="border-radius: 20px">D</button></span>`
        				`<span><button class="btn btn-success btn-sm" v-``on:click="$emit('remove')" style="border-radius: 20px">E</button></span>`
        				`</th>`	
        			`</tr>`
                
        		`</tbody>`
			`</table>`
           ` </paginate>`
           ` <paginate-links for="singers" :simple="{next: 'Next »',prev: '« Back'}"></paginate-links>`
	`</div>`
`<script>`
    `export default {`
        `ready() {`
           ` this.fetchSingersList();`
       ` },`

        `data : function () {`
           ` return{`
                `singers: [],`
              `  paginate: ['singers']`
          `  };`
       ` },`

        `methods : {`
        	`fetchSingersList: function(){`
        		`$.getJSON('/api/choir/singers', function(singer){`
                `this.singers = singer;` 
                `}.bind(this));`
        	`},`

        	`deleteSinger: function(list){`
        		`this.singers.$remove(list);  `
        		`this.$http.delete('/choir/singers/' + list.id, list);`
        	`}`
        `}`
`   }`
`</script>`

Many thanks

**Comment by hemans** [comment]
<img width="664" alt="screen shot 2016-11-22 at 9 44 13 pm" src="https://cloud.githubusercontent.com/assets/12072343/20541287/de053c68-b0fc-11e6-91a9-e58c52232523.png">

**Comment by TahaSh** [comment]
@hemans it obviously won't work since you're using Vue 1.0. `Vue-paginate` v3.0 works only with Vue 2.0. For Vue 1.0, check out [the 1.0 branch](https://github.com/TahaSh/vue-paginate/tree/1.0).
I hope this solves it for you :).

**Comment by hemans** [comment]
Thanks @TahaSh .
