### ISSUE TITLE
<td> instead of <li>

### ISSUE THREAD

**Issue by karneaud** [TahaSh/vue-paginate#24]
Can we do < td > instead of < li >

**Comment by TahaSh** [comment]
@karneaud can you please elaborate more on what you want to accomplish? If you're talking about the `Paginate` component, you can already change that to whatever you want in the slot:

``` html
<paginate
  name="languages"
  :list="langs"
  :per="2"
>
  <td v-for="lang in paginated('languages')">
    {{ lang }}
  </td>
</paginate>
```

**Comment by karneaud** [comment]
Hmmm... strange I did but it outputted a 

```
<ul>
<td>.....</td>
<td>....</td>
....
</ul>

```

I had try setting a **"tag"** property but it didn't work. I moved on though to another package....thanks

**Comment by frangeris** [comment]
`ul` tag its getting printed even in your example @TahaSh [jsfiddle](https://jsfiddle.net/hmapx482/171/)

![jsfiddle](https://user-images.githubusercontent.com/811381/30379780-0204e89e-986e-11e7-9ee7-743bad160cf1.png)

`"vue-paginate": "^3.5.0",`
`"vue": "^2.3.4",`

**Comment by frangeris** [comment]
Here's the solution, the `paginate` component receive a prop named `tag` by default `ul` is used, so:

```javascript
<paginate
  name="orders"
  :list="orders"
  :per="2"
  tag="tbody" // this will replace ul tag by tbody or tr
>
</paginate>
```
