### ISSUE TITLE
Add classes to prev, next links

### ISSUE THREAD

**Issue by tshafer** [TahaSh/vue-paginate#26]
Is their a way to add additional classes to the prev, next li's?

**Comment by TahaSh** [comment]
Thanks Tom for filling this issue! I just released a new version that supports adding additional classes to any element inside PaginateLinks component. [Check the docs for more details](https://github.com/TahaSh/vue-paginate#adding-additional-classes).

**Comment by tshafer** [comment]
Thanks!
