### ISSUE TITLE
Overriding the CONST RIGHT_ARROW = '>>' 

### ISSUE THREAD

**Issue by cmmize** [TahaSh/vue-paginate#27]
First off, thanks for such a useful and well documented component.  

I was wanting to override the const RIGHT_ARROW = '<<'? 
I wanted to use a different indicator and using content=..  in the css didn't work.

Thanks.

**Comment by TahaSh** [comment]
Hey @cmmize! Sorry for the delayed response. You can now customize those links using the new [step links](https://github.com/TahaSh/vue-paginate#step-links) feature.
