### ISSUE TITLE
Property or method "paginated" is not defined

### ISSUE THREAD

**Issue by zcdll** [TahaSh/vue-paginate#29]
`Property or method "paginated" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option. `

`_vm.paginated is not a function`

Hello, when I use this vue-paginate, I use the npm install  command, and add by CommonJS ES6,  and add the example code to a test project.
But I got some errors as above.

Thanks!

**Comment by zcdll** [comment]
I use the vue-webpack to build my project, and add the `import VuePaginate from 'vue-paginate'`  `Vue.use(VuePaginate)` in the main.js file

**Comment by TahaSh** [comment]
Hmm, that's strange! The only reason I can expect this error to happen is if you didn't install the plugin using `Vue.use(VuePaginate)`. Can you please provide me with some more details on how you're using it so I can help you?

**Comment by TahaSh** [comment]
I'm Sorry but I have to close this issue since I haven't heard from you for 10 days. Please re-open it if you still have the problem.

**Comment by kelleysy** [comment]
I'm having the same issue, was there any way to solve this @zcdll
