### ISSUE TITLE
How to apply pagination on data loaded on ready()

### ISSUE THREAD

**Issue by pelletiermaxime** [TahaSh/vue-paginate#3]
Here's the full code for what I'm trying to do https://github.com/pelletiermaxime/wp-rest-ui/blob/466a19a884e477683b1efaf775447dd3ef1f3ce1/src/components/Posts.vue.
Everything works fine if I use the 'posts' array in the data, but if I load data via an ajax request in the ready() function of my component, my 'posts' array is empty.

Any idea ?

**Comment by TahaSh** [comment]
Thanks @pelletiermaxime for mentioning this issue :).

Now it should work. All you have to do, after `npm update`, is updating the full version of the list instead of the paginated.

So, in your code you would do this:

``` js
ready () {
  this.$http.get('wp/v2/posts', {
    order: 'asc',
    filter: {posts_per_page: -1}
  })
    .then(function (response) {
      this.fullPosts = response.data
    }
  )
}
```

**Comment by pelletiermaxime** [comment]
Works perfectly! Thanks for the quick fix and thanks for the great little and useful directive!

**Comment by zchrissirhcz** [comment]
I come up with the same question, and this issue's reference code helps me solve my propble.
However if I set the initial value from `[]` to `''`, then error:

>vue-paginate.js?6bc9:254Uncaught Error: [vue-paginate] the list name "post" is not defined in your vm instance. 

Ok, change it to `[]`. But another problem, the pagination contents still not show (I use vue-cli webpack boilerplate), unless I change the target number to another number.

my vue component code:
```
<template>
      <ol v-paginate:10="post">  // here, attention later
        <li v-for="item in post">
          <a @click="changeLangsPage(item.link)" href="#">
            {{ item.title }}
          </a>
        </li>
      </ol>
</template>

<script>
import VuePaginate from 'vue-paginate'
export default{
  components: {
    VuePaginate
  },
  data () {
    return {
      // attention here! the initial value '' doesn't work, [] work
      // if I change it from '' to [], the webpage still not show pagination contents
      // unless I change the number in'v-paginate:10="post"' (template code above)
      post: ''   
    }
  },
  ready () {
    this.$http({
      url: 'http://mysite/rsite/post',
      method: 'get'
    }).then((response) => {
      var data = JSON.parse(response.data)
      console.log(response)
      if (data.code === 0) {
        this.post = data.msg
        console.log(this.post)
      } else {    // my restful api works fine, and doesn't come to this `else` branch
        this.post = []
      }
    })
  },
```

**Comment by zchrissirhcz** [comment]
@pelletiermaxime I come up with a same problem. By changing the initialization of `posts` variable in `data( )`,  from `posts: [ ]` to `posts: [ { } ]`, things can be better, or if you fresh the page it would show blank in my case.
