### ISSUE TITLE
Limited links is missing three dots

### ISSUE THREAD

**Issue by hedii** [TahaSh/vue-paginate#30]
Hi @TahaSh,

There are some things disturbing in the way paginateLinks are currently shown.

Here are the links from your demo fiddle:

![capture d ecran 2017-01-05 a 11 10 31](https://cloud.githubusercontent.com/assets/5358048/21676825/a8428042-d337-11e6-9d54-889e5b05b2e4.png)

![capture d ecran 2017-01-05 a 11 10 45](https://cloud.githubusercontent.com/assets/5358048/21676828/ab5756ae-d337-11e6-9a1f-7bb4fcd5f0d8.png)

There is no three-dots (...) item on the second picture. Shouldn't it be:

**1** 2 ... 5 >>

<< 1 ... 4 **5**

**Comment by TahaSh** [comment]
Thank you @hedii so much for filling this issue! I think you're totally right. So I released version `v3.3.1` which includes this fix.

**Comment by hedii** [comment]
thanks @TahaSh
