### ISSUE TITLE
Is there a way to use with <transition-group>

### ISSUE THREAD

**Issue by eybarta** [TahaSh/vue-paginate#32]
Hi, I'd really love to use this plugin.. Currently the item list I need to paginate is
wrapped with <transition-group tag="ul"...>, is there an easy way to 
combine the two (with <paginate ... > ) since both need to render the wrapping UL tag?

Thanks for your work!

**Comment by eybarta** [comment]
Never mind, I just wrapped my transition-group with <paginate tag="div" ..> - works perfect! 10X

**Comment by Tomarnst** [comment]
Hi, 

> just wrapped my transition-group with <paginate tag="div" ..>

could you show me how I'm have the same question

**Comment by eybarta** [comment]
sure.. like this:

` <paginate
            name="items"
            :list="items"
            :per="itemsPerPage"
            tag="div"
            class="paginate-langs"
            >
            <transition-group ref="list" name="list" tag="ul" appear
                class="item-list"
                @before-enter="beforeEnter"
                @enter="enter"
                @leave="leave"
                mode="out-in">
                <li v-for="(item, index) in paginated('items')" v-if="!!item" :key="item.id">...</li>
            </transition-group>
        </paginate>`

**Comment by Tomarnst** [comment]
Thanks
