### ISSUE TITLE
Clicking on 'right-arrow' or 'Next' jumps a few pages instead of 1

### ISSUE THREAD

**Issue by eybarta** [TahaSh/vue-paginate#33]
Seems there's a bug when clicking on 'right-arrow', for me it's jumping a few pages.

Also, I need to use the **:limit** option but also change the '»' arrows to 'Next' which seems impossible currently, I might dive into the plugin code to enable this, and would also like to add optional 'First' and 'Last' pager buttons...

Please let me know if what seems to be a bug is, or I'm doing something wrong in my settings. thanks!

**Comment by eybarta** [comment]
Also noticed the 'Next' button disappears and the 'Prev' appears after a few clicks, before it reaches the end of the list..

**Comment by TahaSh** [comment]
> Seems there's a bug when clicking on 'right-arrow', for me it's jumping a few pages

Can you please show me your settings so I can reproduce it?

> Change the '»' arrows to 'Next' which seems impossible currently

I'm currently working on that; the fix will be released soon (related to issue #27)

> Add optional 'First' and 'Last' pager buttons

Can you please elaborate more on this? The limited paginateLinks already shows them, but they're not optional, obviously.

**Comment by TahaSh** [comment]
Ah, now I see what you mean by `jumping a few pages`. This is actually how the plugin works, but I think you're totally right. The arrows should jump one page at a time, and the ellipses should reveal the next chunk of links. I'll include this fix in my next release.

Thank you so much for using the plugin and for filling this issue :).

**Comment by eybarta** [comment]
> Can you please elaborate more on this? The limited paginateLinks already shows them, but they're not optional, obviously.

I was talking about having designated buttons 'first' & 'last' at the edges of the pager.. but if the first and last numbers are always shown I guess that should be enough.. 

Regarding the other issues, thanks for looking into it and fixing.. I'll be waiting on an update :)

**Comment by TahaSh** [comment]
In the latest release, I've added a new feature called [step links](https://github.com/TahaSh/vue-paginate#step-links) which should solve both of your problems.

**Comment by eybarta** [comment]
right on man I'll check it out.. thanks for your work !
