### ISSUE TITLE
Any way to get total pages amount and adding buttons?

### ISSUE THREAD

**Issue by jovanmaric** [TahaSh/vue-paginate#34]
Hey

Is there a way to get the total pages amount? Currently when I apply my filters, it shows the paginate-links, even though only one page is existing. I would like to hide this. 

Also, is it possible to add/inject the left and right arrows to the full paginate-links for traversing the pages?

**Comment by TahaSh** [comment]
Hey @jovanmaric! Thanks a lot for filling this issue. In the latest release, I added a new prop called [hide-single-page](https://github.com/TahaSh/vue-paginate#hide-single-page) to hide that paginateLinks when it contains a single page.

And now you can add those left/right arrows to the full paginate links using the new [step links](https://github.com/TahaSh/vue-paginate#step-links) feature.
