### ISSUE TITLE
Viewing X-Y of Z

### ISSUE THREAD

**Issue by mikerogne** [TahaSh/vue-paginate#35]
GREAT pagination package you've got here. Just tried it out and works beautifully so far.

Just wondering if there's support for something like "Viewing X-Y of Z" already? I didn't see anything like it in the README and I needed it right away so I just created it (pretty simple logic), but if it's already done then that'd be handy too :).

Thanks! Keep up the great work!

**Comment by CalebKester** [comment]
I needed this too so I just wrote up a quick computed function for this. If anyone else cares:
```
		computed: {
			currentPageCount() {
				// Get what page number we're on
				const page = this.paginate.paginatedList.page;
				// Calculate how many total items are in the list
				const numOfItems = this.items.length;
				// first number of the current page
				const first = page * this.perPage;
				// last number of the current page
				const last = Math.min((page * this.perPage) + this.perPage, numOfItems);
				return `${first}-${last} of ${numOfItems}`;
			},
		},
```
@TahaSh if you do pull requests I could page a `<paginate-count>` component for you (or just reuse this).

**Comment by anasred** [comment]
HI Caleb,
How can i make the use of this in the plugin itself? where should i add this code in the plugin and what should i write in the html to view it?

thanks.

**Comment by TahaSh** [comment]
Hey guys! Now version 3.5.0 supports this feature ([see how](https://github.com/TahaSh/vue-paginate#displaying-page-items-count-x-y-of-z)) -- really sorry for the long delay on this feature.
