### ISSUE TITLE
Is there a trick to load items one by one ?

### ISSUE THREAD

**Issue by Tomarnst** [TahaSh/vue-paginate#36]
I have a list and want the list items to load one by one instead of all at once.

**Comment by TahaSh** [comment]
Hey, @Tomarnst! Do you mean animating the list to show items one by one (which is called "staggering list transition")? If so, check out this [jsfiddle](https://jsfiddle.net/taha_sh/8q8pfL7n/). I used the same example code used in Vue's docs in [Staggering list transition section](http://vuejs.org/v2/guide/transitions.html#Staggering-List-Transitions). Note for this to work, you have to include [Velocity.js](http://velocityjs.org/) animating library.

Please don't hesitate to ask for explanation if something isn't clear to you.

**Comment by Tomarnst** [comment]
Thanks,

Working fine ... I could even leave the Velocity part by setting an animation delay method.

Great support thanks again
