### ISSUE TITLE
add href attribute to link paginate 

### ISSUE THREAD

**Issue by vkazakevich** [TahaSh/vue-paginate#38]
bootstrap 
It works poorly if this attribute is not present.
How can I add?

**Comment by stephenjason89** [comment]
same here

**Comment by stephenjason89** [comment]
Has anyone have success in making the cursor look like a pointer  here using bootstrap styling if only 
a has an href='#'

**Comment by larswww** [comment]
Same issue, any solution?

**Comment by OziOcb** [comment]
One solution is to:
1. Copy the entire code from [here](https://github.com/TahaSh/vue-paginate/blob/master/dist/vue-paginate.js) to your project,
2. Find these three functions `getFullLinks, getLimitedLinks, getSimpleLinks` (around line 430+)
3. Inside each of them there's a `data` const, which is an object
4. Add `href` attribute inside those objects like below
```javascript 
const data = {
  attrs: {
    href: "#",
  },
  on: {
    ...
  },
}
```
