### ISSUE TITLE
pagination-links can't be used without its companion <paginate name="...

### ISSUE THREAD

**Issue by z1haze** [TahaSh/vue-paginate#39]
I am paginating table rows but it seems the only place I can get the pagination links to be entered without showing the error in the title of this issue is if I put it in the tfoot.. this is no good because it makes the first column width span as wide as the pagination.

I have attempted to just place the pagination-links after the closing of the table, which it doesnt place them there and it does seem to work, but you I get this error message in the console. Please provide a fix for this.

**Comment by TahaSh** [comment]
Hey! Thanks for filling this issue. Can you please show me some example where it doesn't work (using jsfiddle if possible). I tried to reproduce the issue, but couldn't.

**Comment by z1haze** [comment]
Ok sure.

```
<table>
<paginate name="users-paginate" :list="users" :per="10" tag="tbody">
<tr v-for="user in paginated('users-paginate')">
 ....
</tr>
</paginate>
</table>
<paginate-links</paginate-links>
```

This is basically the setup. and i get 

```
[vue-paginate]: <paginate-links for="users-paginate"> can't be used without its companion <paginate name="users-paginate"> 
(found in component <Users> at C:\projects\laravel-acl-demo\resources\assets\js\components\Users.vue)
```

**Comment by z1haze** [comment]
any luck on this? all these console errors are killing me

**Comment by TahaSh** [comment]
I don't think your issue is related to using the `<table>` element specifically. I think it's because you're using `v-if` either on your `<table>` or on one of its parents. If that's the case, don't worry as my next release will include a fix for it.

You can make sure this is the problem by replacing `v-if` with `v-show`, and if the issue stops happening, then it's the same issue I just mentioned; otherwise let me know.

**Comment by z1haze** [comment]
that was indeed the cause, you say you're going to fix that on the next release? good job this is a nice plugin

**Comment by TahaSh** [comment]
Version 3.5.0 includes a better way to deal with this issue ([check it out](https://github.com/TahaSh/vue-paginate#rendering-paginatelinks-asynchronously)).
