### ISSUE TITLE
How to get the current page number?

### ISSUE THREAD

**Issue by pelletiermaxime** [TahaSh/vue-paginate#4]
I'm trying to add the 'active' class on the links <li> to highlight the current page. To do this I need to get the current page number. Is there a way?
Thanks.

**Comment by TahaSh** [comment]
Thank you @pelletiermaxime, for filling this issue :).

I've updated the plugin to expose the current page number using this convention: `current[listName]Page`. For example, if you're viewing a list of posts, it would be `currentPostsPage`.

So, to add that class to your element all you have to do is comparing each link with the current page, like this:

``` html
<ul>
  <li v-for="postLink in postsLinks">
    <a :class="{ active: currentPostsPage == postLink }" @click="changePostsPage(postLink)" href="#">
      {{ postLink + 1 }}
    </a>
  </li>
</ul>
```

**Comment by pelletiermaxime** [comment]
Thanks!
After your refactor to make it a function, I get the error "Vue is not defined" on the line :
Vue.config.silent = true;

**Comment by TahaSh** [comment]
Oh, sorry! I haven't noticed that because this issue only shows up when you're install it using `Vue.use(VuePaginate)`.

Now, it should be fixed :).
