### ISSUE TITLE
Revert To Page 1 On List Filtering?

### ISSUE THREAD

**Issue by grelca** [TahaSh/vue-paginate#41]
i'm finding it very inconsistent that the page reverts to 1 in the case that i filter the item list and there are no items on the current page. instead, about half the time it stays on the current page, even if that page is empty.

right now i'm working around this with the following code:

```javascript
$('ul.paginate-links > li.number > a')[0].click();
```

which works fine, but the problem also means that i can't use the hide-single-page option, because there's a good chance that if i filter while already on page 3, it'll show me an empty page and i need the pagination links to actually get to page 1.

beyond that, i feel like there should be a way to revert to page 1 even _if_ page 3 still has results, because it just seems very weird to me that i'd change/filter the results without moving back to page 1.

**Comment by grelca** [comment]
i was browsing the other issues and it looks like this was because of my paginated list being inside of a v-if, like the error about the links needing its companion. i changed from v-if to v-show and it has been working correctly since :)

**Comment by TahaSh** [comment]
@grelca in version 3.5.0, you can change it back to `v-if` and use `:async="true"` on your `<paginate-links>` component. [Check out the docs for more details](https://github.com/TahaSh/vue-paginate#rendering-paginatelinks-asynchronously).
Thanks for filling this issue. Enjoy the plugin :).
