### ISSUE TITLE
Trigger next page with a method call.

### ISSUE THREAD

**Issue by dannynpham** [TahaSh/vue-paginate#43]
Hey, great work on the plugin! I was wondering is there a way to trigger a page change with a method call? I want to trigger a page change with a key up event, but I can't seem to find the way to do it without using paginate-link tag.

**Comment by dannynpham** [comment]
For the time being I'm using this shortcut to trigger the method call. 
`switch (keyCode) {
    case 56: {
      const prevEl = document.querySelector('.prev').children[0];
      if (prevEl) {
        prevEl.click();
      }
      break;
    }
    case 57: {
       const nextEl = document.querySelector('.next').children[0];
       if (nextEl) {
         nextEl.click();
       }
       break;
  }`

**Comment by TahaSh** [comment]
@dannynpham in version 3.5.0 you can use `goToPage(pageNumber)` method to navigate pages programmatically. [Learn about it from the docs](https://github.com/TahaSh/vue-paginate#navigate-pages-programmatically).
