### ISSUE TITLE
vue-paginate has stopped developing?

### ISSUE THREAD

**Issue by vinayakkulkarni** [TahaSh/vue-paginate#50]
Has the development stopped? it's been 3 months since last release (v3.4.0 on 17 Jan)

Are there any plans for the next release and/or bug fixes or even issues being answered?

**Comment by TahaSh** [comment]
@vinayakkulkarni You're right. It's been a very long time. I'm now working on releasing v3.5.0 which should fix most of the issues (if not all). Thanks for your patience!
