### ISSUE TITLE
Register list dynamically

### ISSUE THREAD

**Issue by saintplay** [TahaSh/vue-paginate#55]
**Hi**, I'm having trouble in this particular scenario!
```js
window.willow = new Vue({
    el: '#content-wrapper',
    data: {
        workers: [],
        customers: [],
        contracts: [],
        incomes: [], // I need pagination for this list
        funds: [],
        paginate: [] // For some reason I don't want to  register 'incomes' here
    }
});

// In other place
willow.paginate = ['incomes'];
// or
willow.paginate.push('incomers')

```

But of course, this doesn't work.
There is any workaround I can use to archive this problem?

Thanks in advance

**Comment by frangeris** [comment]
I think this is not relative to the package itself, it's about vue architecture, about [reactivity](https://vuejs.org/v2/guide/reactivity.html), `data` it's encapsulated inside a `vm`, data is not a global variable that you can update from outside of scope.

What you're trying to do is known as flux architecture, use the vue implementation [vuex](vuex.vuejs.org), using the concept of "source of truth", here's an [example](https://vuex.vuejs.org/en/getting-started.html)

**Comment by saintplay** [comment]
It seems like Vue 3.0 will come with a better reactive system and will support adding new properties

**Comment by saintplay** [comment]
At that time, I didn't know about Vuex, so, a few weeks ago I did some refactoring with Vuex, and this is no longer a problem for me,

I think a that time I was doing many bad practices.

I don't know if I should close this issue.
