### ISSUE TITLE
How do I change the full version of the list

### ISSUE THREAD

**Issue by DannyFeliz** [TahaSh/vue-paginate#6]
Hi, I was wondering how you change the full version of the list, I know that this array is generated dinamically but what about if I want to change the full version of array of the list with some new data?

**Comment by TahaSh** [comment]
This was already added in [version 1.1.1](https://github.com/TahaSh/vue-paginate/releases/tag/v1.1.1).

By the way, I'm currently working on version 2.0, which will contain a couple more features (including the one you requested in [the previous issue](https://github.com/TahaSh/vue-paginate/issues/5)). Also, I'll update the readme to provide a full explanation of how everything works. So, stay tuned :).
