### ISSUE TITLE
Error in getter for watcher "currentPage"

### ISSUE THREAD

**Issue by MortezaAghili** [TahaSh/vue-paginate#65]
We're using two components called **VueFormWizard**, **vue-paginate**. when we use vue-paginate in VueFormWizard for sorting our data, we get an error like this: 

> [Vue warn]: Error in getter for watcher "currentPage": "TypeError: Cannot read property 'allQuestions' of undefined"

[![screenshot from our error][1]][1]

our code:

    {{getAllQuestions}}
    <paginate name="allQuestions" :list="allQuestions" :per="2">
      <div class="" v-for="quest in paginated('allQuestions')">
        <label v-bind:class="{selectedQuestionClass:quest==selectedQuestion}"
               @click="selectQuestion(quest)"
               class="form-control allQuest">{{quest.description}}</label>

      </div>
    </paginate>
    <paginate-links for="allQuestions"></paginate-links>

p.s : **getAllQuestions** is a function for retrive all data from our RESTFul API thats get an array.

 

 

  [1]: https://i.stack.imgur.com/hEcea.png

**Comment by mogita** [comment]
I've met the same issue and likely found some clues. `Paginate` can't be placed in a slot (ref https://github.com/TahaSh/vue-paginate/issues/48), or between the `transition`/`transition-group` tags.

You can output `this.$parent` at around line 78 in `vue-paginate/dist/vue-paginate.js` to see the cause.

My solution is to create a `.vue` file and move the part related to `paginate` in that file, together with the list $data properties, then import the component and place it inside my `transition` tags. It works this way.

**Comment by kelleysy** [comment]
I was getting the same error as above
thanks @mogita your solution worked, I created its own component

**Comment by TahaSh** [comment]
Yeah, you can fix it by wrapping the pagination in a new component (thanks @mogita for the suggestion), or you can use [the new `container` prop](https://github.com/TahaSh/vue-paginate#using-it-inside-a-components-slot) to specify what component contains the current state of the pagination.
