### ISSUE TITLE
Style li items inline

### ISSUE THREAD

**Issue by charlesnjihia** [TahaSh/vue-paginate#83]
I have tried to apply the following css to make the list items to arrange inline but it still does not get effected
```
ul.paginate-links
{
margin: 0;
padding: 0;
list-style-type: none;
background-color: white;
}

li.number  
{
display: inline;
}
```

Any solution for this please?

**Comment by PascalGit1** [comment]
@charlesnjihia 
I have the same issue, even when putting it on inline and using the css classes in the example it keeps displaying them underneath each other.
How did you manage to fix this?
